### ISSUE TITLE
Importing .Game

### ISSUE THREAD

**Issue by ninjassifi** [gurkenlabs/litiengine-docs#10]
I have been following your tutorial for a long time, I put all the correct information from your article into build.gradle, but the import does not function:

![image](https://user-images.githubusercontent.com/71397710/109443584-c25dbd80-79ef-11eb-89d5-9de87a5e756a.png)

I also sometimes get confused. If the code is supposed to go somewhere else please let me know.
Code for build.gradle:

![image](https://user-images.githubusercontent.com/71397710/109443327-1b792180-79ef-11eb-95b1-f6ce38f85fb6.png)

If you need more information, please ask for specific information. I don't know what else to put here.

---
#### Document Details

*Do not edit this section.* ⚠

* Version: master
* Page: docs/getting-started/run-the-game
* Content: [Run the Game](https://litiengine.com/docs/getting-started/run-the-game/)
* Content Source: [getting-started/run-the-game.md](https://github.com/gurkenlabs/litiengine-docs/tree/master/getting-started/run-the-game.md)

**Comment by ninjassifi** [comment]
Also, If you were wondering, I am using Intellij community edition 2020.2.3

**Comment by nightm4re94** [comment]
The issue here is that you are mixing up actual game code with the gradle build script. 
Everything from Line 27 does not belong in the gradle build script, but an actual class `Program` in your project.

**Comment by ninjassifi** [comment]
Thank you! I did not know what you meant by 'class', So I just put it in build.gradle.
