### ISSUE TITLE
Migrate "Getting Started" Blog posts

### ISSUE THREAD

**Issue by steffen-wilke** [gurkenlabs/litiengine-docs#2]
In an effort to unify our documentation, we're aiming to migrate (some) Wordpress blog posts to the Markdown format we use for the rest of the documentation to enable collaboration, reduce maintenance effort and unify the Look and Feel of the docs.

- [x]  https://litiengine.com/getting-started-setup-the-game-project/
- [x]  https://litiengine.com/getting-started-learning-the-basics/ 
- [x]  https://litiengine.com/getting-started-configuring-the-game/

**Comment by patricksan** [comment]
Maybe use the GitHub pages to make it simple to change?

**Comment by steffen-wilke** [comment]
That's a reasonable suggestion and we've considered this in the past.

Previously, we've hosted the documentation on GitBook which kind of did the same but it was hosted externally. For our new web presence, we're aiming to unify the experience and the docs will be integrated into our WordPress page. For this purpose, I've written a WordPress plugin that dynamically fetches the contents from GitHub for our upcoming new Website. So changes made to this repository (`wp-docs` branch for now) will be automatically updated on the documentation pages.
