### ISSUE TITLE
Nonexisting method in tutorial

### ISSUE THREAD

**Issue by evilSwanson** [gurkenlabs/litiengine-docs#6]
The the two occurrences of  `setIconImage(...)` should be `setIcon(...)` because there is no `setIconImage` method.

---
#### Document Details

*Do not edit this section.* ⚠

* Version: master
* Page: docs/tutorials/creating-a-platformer
* Content: [Creating a platformer with LITIENGINE](https://litiengine.com/docs/tutorials/creating-a-platformer/)
* Content Source: [tutorials/creating-a-platformer.md](https://github.com/gurkenlabs/litiengine-docs/tree/master/tutorials/creating-a-platformer.md)

**Comment by nightm4re94** [comment]
Thank you, fixed it.
