### ISSUE TITLE
More Gurk Nukem feedback

### ISSUE THREAD

**Issue by evilSwanson** [gurkenlabs/litiengine-docs#7]
- Nonexisting method: The `addLoadedListener`-method in the `GurkNukemLogic` should be `onLoaded`

- > You're probably wondering why we've chosen 4.001 as a scaling factor; Simply put: There is currently a bug doing some very ugly stuff when scaling sprites with whole numbered factors.
 
Is this still relevant? I see horizontal black lines WITH that scaling factor:
![image](https://user-images.githubusercontent.com/35380225/97110688-85488e00-16d2-11eb-9e9c-a1ec3961c535.png)
But that bug is gone with something like `4.000`.

---
#### Document Details

*Do not edit this section.* ⚠

* Version: master
* Page: docs/tutorials/creating-a-platformer
* Content: [Creating a platformer with LITIENGINE](https://litiengine.com/docs/tutorials/creating-a-platformer/)
* Content Source: [tutorials/creating-a-platformer.md](https://github.com/gurkenlabs/litiengine-docs/tree/master/tutorials/creating-a-platformer.md)

**Comment by nightm4re94** [comment]
The outdated method name has been updated. 
As the scaling problem is not really a documentation problem, I would close this issue now.
